# 如有必要，首先构建基础镜像（参见 Dockerfile）
# - 如果本地未构建，将拉取远程镜像。
# 然后，使用以下命令构建：
#	docker build -t ghcr.io/termux/package-builder-cgct --file Dockerfile.cgct .
# 使用以下命令推送到 GitHub 镜像仓库：
#	docker push ghcr.io/termux/package-builder-cgct
# 在修改此文件或以下任一设置脚本后执行此操作：
# scripts/setup-{ubuntu,android-sdk,cgct}.sh
FROM ghcr.io/termux/package-builder
RUN TERMUX_PKGS__BUILD__IS_DOCKER_BUILD='true' /tmp/termux-packages/scripts/setup-cgct.sh
